trainer:
    name: MiniCastleNoSamplePool
    min_steps: 48
    max_steps: 64
    visualize_output: false
    device_id: 0
    use_cuda: true
    num_hidden_channels: 10
    use_sample_pool: false
    model_config:
        normal_std: 0.1
        update_net_channel_dims: [32, 32]
    optimizer_config:
        lr: 0.002
    dataset_config:
        nbt_path: structs_dataset/nbts/mini_castle.nbt

defaults:
  - voxel